version: "3.8"

# user-defined variables (in order: base-image name, base-image version and directory to be bound)
x-var0: &BASE_IMAGE
  debian
x-var1: &BASE_VERSION
  latest
x-var2: &SHARED_DIR
  ./app

services:
  dit:
    build:
      context: ./docker
      args:
        BASE_IMAGE: *BASE_IMAGE
        BASE_VERSION: *BASE_VERSION
    image: docker-interactive-tool
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: *SHARED_DIR
        target: /dit/usr