version: "3.8"

# user-specified build ARGs  (can also be overwritten by '--build-arg key=val')
x-var0: &BASE_NAME
  debian
x-var1: &BASE_VERSION
  latest

# user-defined variables  (cannot be edited on the command line when using 'docker-compose')
x-var2: &IMAGE_NAME
  debian-dit
x-var3: &SHARED_DIR
  ./app


services:
  dit:
    build:
      context: ./docker
      args:
        BASE_NAME: *BASE_NAME
        BASE_VERSION: *BASE_VERSION
    image: *IMAGE_NAME
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: *SHARED_DIR
        target: /dit/mnt