version: "3.8"

# user-defined variables (in order: base-image name, base-image version, image name and shared directory)
x-var0: &BASE_NAME
  debian
x-var1: &BASE_VERSION
  latest
x-var2: &IMAGE_NAME
  debian-dit
x-var3: &SHARED_DIR
  ./app

services:
  dit:
    build:
      context: ./docker
      args:
        BASE_NAME: *BASE_NAME
        BASE_VERSION: *BASE_VERSION
    image: *IMAGE_NAME
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: *SHARED_DIR
        target: /dit/mnt