version: "3.8"

# user-defined variables (in order: base-image name, base-image version and directory to be bound)
x-var0: &BASE
  debian
x-var1: &VERSION
  latest
x-var2: &SHARED_DIR
  ./app

services:
  dit:
    build:
      context: ./docker
      args:
        BASE: *BASE
        VERSION: *VERSION
    image: docker-interactive-tool
    network_mode: "none"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: *SHARED_DIR
        target: /dit/share