version: "3.8"


services:
  dev:
    build:
      context: ./docker
      target: "${BUILD_TARGET:?}"
      args:
        BASE_NAME: "${BASE_NAME:?}"
        BASE_VERSION: "${BASE_VERSION:?}"
    image: "dit-${BASE_NAME}:${IMAGE_TAG:-latest}"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: "${SHARED_DIR:?}"
        target: /dit/mnt